# Generated by Django 5.0.1 on 2025-11-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=50, unique=True, verbose_name='Numer kolczyka')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('breed', models.CharField(default='Highland Cattle', max_length=100, verbose_name='Rasa')),
                ('birth_date', models.DateField(verbose_name='Data urodzenia')),
                ('gender', models.CharField(choices=[('M', 'Samiec'), ('F', 'Samica')], default='F', max_length=1, verbose_name='Płeć')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cows/', verbose_name='Zdjęcie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Krowa',
                'verbose_name_plural': 'Krowy',
                'ordering': ['-created_at'],
            },
        ),
    ]
