# Generated by Django 5.0.1 on 2025-11-01 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LECZENIE', 'Leczenie'), ('SZCZEPIENIE', 'Szczepienie'), ('WYCIELENIE', 'Wycielenie'), ('KONTROLA', 'Kontrola'), ('INNE', 'Inne')], default='INNE', max_length=50, verbose_name='Typ zdarzenia')),
                ('date', models.DateField(verbose_name='Data zdarzenia')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cows.cow', verbose_name='Krowa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Zdarzenie',
                'verbose_name_plural': 'Zdarzenia',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
